version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - evanlihou
  ignore:
  - dependency-name: node-sass
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: react-big-calendar
    versions:
    - 0.31.0
    - 0.32.0
    - 0.33.0
    - 0.33.1
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
